spring:
  profiles:
    active: dev
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-PROVIDER
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml #设置mapper.xml的路径
  type-aliases-package: cn.itsource.aigou.domain #设置别名
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-PROVIDER
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml #设置mapper.xml的路径
  type-aliases-package: cn.itsource.aigou.domain #设置别名