spring:
  profiles:
    active: dev
---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
zuul:
  prefix: /aigou
  ignored-services: "*"
  routes:
    plat.serviceId: user-provider
    plat.path: /plat/**
    product.serviceId: product-provider
    product.path: /product/**
---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
zuul:
  prefix: /aigou
  ignored-services: "*"
  routes:
    plat.serviceId: user-provider
    plat.path: /plat/**
    product.serviceId: product-provider
    product.path: /product/**